apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "isso.fullname" . }}
  labels:
    {{- include "isso.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "isso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "isso.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "isso.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ISSO_SETTINGS
              value: "/config/isso.conf"
          args:
            - "/isso/bin/gunicorn"
            - "-b"
            - "0.0.0.0:8080"
            - "-w"
            - "4"
            - "--preload"
            - "isso.run"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
          volumeMounts:
          - name: config-volume
            mountPath: /config/
          - mountPath: /var/lib/isso/
            name: data
            subPath: isso
      volumes:
        - name: config-volume
          configMap:
            name: isso
        - name: data
          persistentVolumeClaim:
            claimName: "{{ include "isso.fullname" . }}-data"
